export VK_API_TOKEN=<YOUR_VK_TOKEN>
export TELEGRAM_BOT_TOKEN=<YOUR_TELEGRAM_BOT_TOKEN>
export TELEGRAM_API_HASH=<YOUR_TELEGRAM_API_HASH>
export TELEGRAM_API_ID=<YOUR_TELEGRAM_API_ID>
export TELEGRAM_USER_ID=<YOUR_TELEGRAM_USER_ID>

python3 main.py
